# ----------
# GNUmakefile
#
#     Copyright (c) 2023 Marc Munro
#     Fileset:	libbgpiod - basic/bloodnok gpio device library
#     Author:   Marc Munro
#     License:  GPL-3.0
#
# ----------
#

############################################################# 
# Run make in the parent directory.  This allows make to be run in
# this directory without a proper makefile, which allows tools like
# emacs next-error to work as you would want.
#
DEFAULT:

%::
	cd ..; $(MAKE) $@
